# Generated by Django 2.2.24 on 2022-12-09 10:12

from django.db import migrations


def fill_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_buildings = Flat.objects.filter(construction_year__gte=2015)
    new_buildings.update(new_building=True)
    old_buildings = Flat.objects.filter(construction_year__lt=2015)
    old_buildings.update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221202_1857'),
    ]

    operations = [
        migrations.RunPython(fill_new_buildings),
    ]
