# Generated by Django 2.2.24 on 2022-12-28 10:07

from django.db import migrations


def move_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            normalized_phonenumber=flat.normalized_owners_phonenumber,)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners)
    ]
