# Generated by Django 2.2.24 on 2023-02-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221228_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='normalized_owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
